### ISSUE TITLE
Replace references to {{ STATIC_URL }} variable with {% static %} template tag

### ISSUE THREAD

**Issue by thaisviana** [thaisviana/AlgPedia#2]
All html pages

**Comment by jonvelasco** [comment]
I started doing it today!!
Let's DO this!

**Comment by jonvelasco** [comment]
While I was replacing references I came up to a template called "accounts/signin.html", but I couldn't find it in "templates" folder. Than I realized that there is NO template for login, so when someone tries to login it shows na error page.
![image](https://user-images.githubusercontent.com/33075264/33718854-ff58dd10-db45-11e7-8229-9d0d12d46d65.png)

**Comment by jonvelasco** [comment]
All html static files referencies replaced!
Now it takes only a test to close the issue!
